version: '3.9'

services:
  dev_backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/src
    ports:
      - "8000:8000"
    command:
      gunicorn backend.wsgi --bind=0.0.0.0:8000
  stg_backend:
    build:
      context: .
      dockerfile: Dockerfile.stg
    image: docker-django/stg_backend