FROM python:3.10
ENV PYTHONUNBUFFERED 1

RUN mkdir /src
WORKDIR /src

ADD ./backend/requirements.txt /src
RUN pip install -r requirements.txt

COPY ./backend /src

EXPOSE 80
CMD ["gunicorn", "backend.wsgi", "--bind=0.0.0.0:80"]